### ISSUE TITLE
how do we deal with job.py?

### ISSUE THREAD

**Issue by ilanasegall** [bwinton/AustralisTelemetry#10]
many solutions:
-make a job2.py that takes a dict config (gross - won't get updates)
-feed in a namedtuple to original job to keep the dot notation (also gross - hard to update/read code and bloat)
-require everyone the use the new job.py and take in a dict or **kwargs (grossest)

**Comment by ilanasegall** [comment]
-talk to mreid; extend job.py, take kwargs? allow to pass in a dict??

**Comment by mreid-moz** [comment]
What do you need to change in job.py?

**Comment by ilanasegall** [comment]
Essentially, we want to change the arguments coming into the **init** to be in dictionary form:
-more pythonic 
-easier passing of arguments to the Job class when not through the command line
-easier to add new arguments and handling to **init**

This consists of the changes seen here: https://github.com/ilanasegall/AustralisTelemetry/blob/master/telemetry-server/mapreduce/job.py (also in the open pull request here), and additional code to coerce the Namespace object into a dictionary like so:

args = args.**dict**
job = Job(args) 

Thus, all the functionality will be the same on your end.

**Comment by mreid-moz** [comment]
That sounds fine to me.

**Comment by ilanasegall** [comment]
pushed to /mozilla/telemetry-server
